[package]
name = "fuzzer"
version = "1.0.0"
authors = ["sam <sunhaoyl@outlook.com>"]
edition = "2018"

[dependencies]
core = {path="../core"}
executor = {path = "../executor"}
fots={path="../fots"}
serde ={ version= "1.0.104" ,features = ["derive"]}
bincode = "1.2.1"
lazy_static = "1.4.0"
port_check = "0.1.5"
toml = "0.5.6"
structopt = {version="0.3.7",default-features=true}
exitcode = "1.1.2"
os_pipe = "0.9.1"
nix = "0.17.0"
itertools = "0.8.2"
chrono = { version = "0.4.10", features = ["serde"] }
serde_json = "1.0.48"
circular-queue = "0.2.3"
log = "0.4"
log4rs = "0.11.0"
lettre = "0.9"
lettre_email = "0.9"
native-tls = "0.2.4"
num_cpus = "1.0"
signal-hook = "0.1.13"
rayon-core = "1.7.0"